version: '2'

networks:
  socketionet:
    driver: bridge

services:
  socketio-chat:
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'dimaskiddo/socketio-chat:latest'
    networks:
      - socketionet
    ports:
      - 3000:3000
    environment: 
      - SOCKETIO_REDIS_HOST=socketio-redis
      - SOCKETIO_REDIS_PASS=socketio-redis
    depends_on:
      - socketio-redis
    restart: always

  socketio-redis:
    image: 'dimaskiddo/alpine:redis-3.2'
    networks:
      - socketionet
    environment: 
      - REDIS_PASSWORD=socketio-redis
    restart: always
