version: '2'

networks:
  socketionet:
    driver: bridge

services:
  socketio-chat:
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'dimaskiddo/socketio-chat:latest'
    networks:
      - socketionet
    ports:
      - 3000:3000
    restart: always
